### ISSUE TITLE
Twitter is not working

### ISSUE THREAD

**Issue by ThomasMentzel** [awesome-inc/hello.kibana#4]
Activating the twitter configuration for the ELK stack produces an error. I added the access token as environment variables.

{:timestamp=>"2016-05-23T11:13:04.788000+0000", :message=>"undefined method `filter' for nil:NilClass", :exception=>#<NoMethodError: undefined method `filter' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter.rb:128:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:336:in `start_input'"], :options=>nil, :level=>:warn}

**Comment by ThomasMentzel** [comment]
Current issue:

{
     : timestamp = > "2016-05-23T13:55:18.758000+0000",
     : message = > "",
     : exception = > Twitter::Error::BadRequest,
     : backtrace = > [
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete'",
     "org/ruby_http_parser/RubyHttpParser.java:370:in `<<'", 
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:16:in `<<'",
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter/patches.rb:31:in `stream'",
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter/patches.rb:58:in `request'", 
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'",
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter.rb:128:in `run'",
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha2-java/lib/logstash/pipeline.rb:388:in `inputworker'",
     "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha2-java/lib/logstash/pipeline.rb:382:in `start_input'"],
     : options = > nil,
     : level = > : warn
}

**Comment by mkoertgen** [comment]
@ThomasMentzel making progress.

We discussed route events to different document_types. We can use implicit `event[type]` for that, cf.: [logstash-output-elasticsearch docs](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-document_type)

**Comment by mkoertgen** [comment]
For the rss2-plugin i added code+test that adds the type from config (default: `rss`)

**Comment by mkoertgen** [comment]
By now (5.0.0-alpha3) , the [logstash-input-twitter](https://github.com/logstash-plugins/logstash-input-twitter)-plugin has [issues](https://github.com/logstash-plugins/logstash-input-twitter/issues) that prevent it from working.

**Comment by mkoertgen** [comment]
Still about 17 open issues with the twitter plugin. We will abandon the twitter plugin for now.
