### ISSUE TITLE
Show keywords

### ISSUE THREAD

**Issue by ThomasMentzel** [awesome-inc/hello.kibana#9]
It would be useful to show the top x extracted keywords. It makes sense to use the tag cloud. 

https://github.com/stormpython/tagcloud

**Comment by mkoertgen** [comment]
Good idea

**Comment by mkoertgen** [comment]
Here is meant to show some sort of top trends

**Comment by mkoertgen** [comment]
Using `"fielddata": true` on the `title` field should be ok. Then using a [significant terms](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-significantterms-aggregation.html) aggregation excluding terms smaller than 5 chars (`.{0,5}`)
